### ISSUE TITLE
"from pydsm.input import parser" results in error

### ISSUE THREAD

**Issue by ZhenlinZhang** [CADWRDeltaModeling/pydsm#3]
* pydsm version: 0.2.5
* Python version: 3
* Operating System: windows

### Description
from pydsm.input import parser
Traceback (most recent call last):

  File "<ipython-input-24-eb395b5d33a0>", line 1, in <module>
    from pydsm.input import parser

ModuleNotFoundError: No module named 'pydsm.input'

**Comment by dwr-psandhu** [comment]
@ZhenlinZhang I am not able to reproduce this error. Can you do the install commands on a new environment and confirm ?
`
conda create -y -n dsm2 -c cadwr-dms -c defaults python=3.7* pydsm
`
Also reply with conda info and conda list --show-channel-urls command outputs.

**Comment by ZhenlinZhang** [comment]
Thanks, Nicky! Sorry, I did need update my pydsm.
