### ISSUE TITLE
tsmath.nash_sutcliffe bug

### ISSUE THREAD

**Issue by ZhenlinZhang** [CADWRDeltaModeling/pydsm#35]
It seems that NSE should be     
den = mse(series2, series2.mean())
num = 1-mse(series1, series2)/den

**Comment by dwr-psandhu** [comment]
Can you give me a reference for NSE?

**Comment by ZhenlinZhang** [comment]
Yes, I followed the link in the function: https://en.wikipedia.org/wiki/Nash%E2%80%93Sutcliffe_model_efficiency_coefficient

**Comment by dwr-psandhu** [comment]
Agreed. Fixed by latest commit.

**Comment by ZhenlinZhang** [comment]
Thank you!
